type User{
    login: String!
    id: Int
    avatar_url: String
    type: String
    name: String!
    roles: Roles
}

type Friend {
  name: String
}

type Roles {
    user: User!
    admin: Boolean!
}

type Query {
    user: User
    friend: [Friend]
    roles: Roles!
}

type Mutation {
  addFriend(name: String!): [Friend]
}