interface Pet {
  name: String!
  age: Int
  type: String
}

type Dog implements Pet {
  name: String!
  age: Int
  type: String
  breed: String
}

type Cat implements Pet {
  name: String!
  age: Int
  type: String
  furColor: String
}

type Parrot implements Pet {
  name: String!
  age: Int
  type: String
  color: String
}

type Person {
  name: String
  age: Int
}

extend type Query {
  myCat: Cat
  myDog: Dog
  myParrot: Parrot
  myPets: [Pet]
  persons: [Person]
}