
type Dog {
  name: String!
  age: Int
  breed: String
}

type Cat {
  name: String!
  age: Int
  furColor: String
}

type Parrot {
  name: String!,
  age: Int,
  color: String
}

type Person {
  name: String
  age: Int
}

extend type Query {
  myCat: Cat
  myDog: Dog
  myParrot: Parrot
  persons: [Person]
}